import './globals.css';
import localFont from 'next/font/local';
import { Josefin_Sans } from 'next/font/google';

const calSans = localFont({
  src: './CalSans-SemiBold.woff2',
  variable: '--font-cal-sans',
  display: 'swap',
});
const josefinSans = Josefin_Sans({
  variable: '--font-josefin',
  display: 'swap',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={`bg-stone-900 ${calSans.variable} ${josefinSans.variable} font-josefin text-stone-200`}
      >
        {children}
      </body>
    </html>
  );
}
